#!/usr/bin/env bash

ulimit -n 2048

[ -z "$LENGTH_OF_TEST" ]         && LENGTH_OF_TEST="1"
[ -z "$EMAILS_PER_MINUTE" ]      && EMAILS_PER_MINUTE="500"
[ -z "$ENABLE_CHAOS" ]           && ENABLE_CHAOS="true"
[ -z "$ENABLE_PROFILER" ]        && ENABLE_PROFILER="false"
[ -z "$RUBY_PROF_MEASURE_MODE" ] && RUBY_PROF_MEASURE_MODE="process"

clear

echo
echo "Did you set up database? Postgres works best, and you need to run this:"
echo "$ RAILS_ENV=stress rake db:drop db:create db:setup db:seed"
echo
echo "The goal of this stress test is to ensure that:"
echo
echo "1. CPU load remains stable."
echo "2. Memory remains stable."
echo "3. IO handles are properly closed."
echo "4. The system actually reads all of the email."
echo
echo "Use system tools to monitor #1, #2, and #3."
echo "View 'stress-test-results.pdf' for #4."
echo
echo "By design, the stress test generates bad IMAP responses."
echo "These will look like exceptions in the imap_client process."
echo "Do not be alarmed; you can ignore the errors."
echo
echo "Some useful environment variables to set:"
echo
echo "+ LENGTH_OF_TEST         - Total number of minutes to run test. [$LENGTH_OF_TEST]"
echo "+ EMAILS_PER_MINUTE      - Rate of fake email generation. [$EMAILS_PER_MINUTE]"
echo "+ ENABLE_CHAOS           - 'true' if we should generate bad IMAP responses. [$ENABLE_CHAOS]"
echo "+ ENABLE_PROFILER        - 'true' to start the ruby-prof profiler. [$ENABLE_PROFILER]"
echo "+ RUBY_PROF_MEASURE_MODE - What should ruby-prof measure? [$RUBY_PROF_MEASURE_MODE]"
echo "                         - Can be 'wall', 'process', 'cpu', 'allocations', 'memory', 'gc_time', or 'gc_runs'"
echo "                         - See https://github.com/ruby-prof/ruby-prof"
echo
echo "Press enter to continue, Control-C to exit."
read

echo "Beginning stress test. Please wait."

# Remove old log files.
rm ./log/stress/*

# Begin the stress test.
RAILS_ENV=stress foreman s -f Procfile.stress-test

# Generate some plots.
Rscript script/analyze-stress-test.R

echo
echo "Stress test results are in 'tmp/stress-test-results.pdf'."
echo "If enabled, profiler results are in 'tmp/profile.html'."
echo
